### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by dragonfly4** [SendCloud/sendcloud#121]
PHP 7.4 is EOL and PHP 8.0 is available for 1 year. When will Sendcloud support PHP 8.0.x please?
https://www.php.net/supported-versions.php

https://github.com/SendCloud/sendcloud/blob/master/composer.json#L9

`  "name": "sendcloud/sendcloud",
  "description": "A Magento 2 module that connects the Magento environment to the SendCloud environment",
  "type": "magento2-module",
  "homepage": "https://www.sendcloud.com/",
  "license": "Apache-2.0",
  "version": "1.8.0",
  "require": {
    "php": "~7.0|~7.1|~7.2|~7.3|~7.4"
  },`

Or are we missing the latest 1.8.2 release on Guthub?
https://marketplace.magento.com/sendcloud-sendcloud.html#product.info.details.release_notes

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
