### ISSUE TITLE
Error when upgrading to version 1.8.2 (using Composer)

### ISSUE THREAD

**Issue by DJB95** [SendCloud/sendcloud#122]
When upgrading to the latest version using Magento Marketplace (using Composer), I'm getting this error after setup:upgrade command:

SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'sen_condition_name' doesn't exist in table, query was: ALTER TABLE `sendcloud_servicepointrate` DROP COLUMN `sen_condition_name`, ADD CONSTRAINT `UNQ_C0DB67076EAA5EA868F15196691297E7` UNIQUE KEY (`website_id`,`dest_country_id`,`dest_region_id`,`dest_zip`,`condition_name`,`condition_value`)

When checking the table, the column DOES exist
![image](https://user-images.githubusercontent.com/74458320/151368009-4e6761f6-fd1a-4fbd-95ac-32a764e6faf4.png)

Can you tell me how I can fix this?

**Comment by bamboekeizer** [comment]
I have the same issue. But how is it possible the upgraded version is 1.8.2 while according to github version 1.8.0 is the latest?
  - Updating sendcloud/sendcloud (1.8.0 => 1.8.2): Loading from cache

**Comment by DJB95** [comment]
@bamboekeizer I've been in contact with them. should be fixed somewhere next week. update from Magento Marketplace
https://marketplace.magento.com/sendcloud-sendcloud.html

temporary fix would be to downgrade back to 1.8.0 (I did this to fix it for the time being)

**Comment by michel334** [comment]
Same error is in Sendcloud version 1.8.3 using composer (magento version 2.3.2)

$ COMPOSER_MEMORY_LIMIT=-1 composer require sendcloud/sendcloud
Using version ^1.8 for sendcloud/sendcloud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating sendcloud/sendcloud (1.8.0 => 1.8.3): Downloading (100%)



$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
Updating modules:
Schema creation/updates:
SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'sen_condition_name' doesn't exist in table, query was: ALTER TABLE `sendcloud_servicepointrate` DROP COLUMN `sen_condition_name`, ADD CONSTRAINT `UNQ_C0DB67076EAA5EA868F15196691297E7` UNIQUE KEY (`website_id`,`dest_country_id`,`dest_region_id`,`dest_zip`,`condition_name`,`condition_value`)

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
