### ISSUE TITLE
Unable to install Sendcloud version 1.8.2 with composer

### ISSUE THREAD

**Issue by michel334** [SendCloud/sendcloud#123]
We want to upgrade to Magento version 2.4.3 and we need Sendcloud 1.8.2 for this but unable to install 1.8.2 using composer

composer show sendcloud/sendcloud -all

name     : sendcloud/sendcloud
descrip. : A Magento 2 module that connects the Magento environment to the SendCloud environment
keywords :
versions : dev-master, 1.8.0, 1.7.1, 1.7.0, 1.6.1, 1.6.0, 1.5.0, 1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.2, 1.1.1, 1.1.0, 1.0.20, 1.0.19, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, dev-bugfix/1.6.0, dev-release/1.8.0, dev-release/1.7.0, dev-release/1.6.1, dev-feature/SEN-259, dev-feature/SEN-249, dev-hotfix/tablerate, dev-update-version
latest   : 1.8.0
type     : magento2-module
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : https://www.sendcloud.com/
source   : [git] https://github.com/SendCloud/sendcloud.git 0765af9337cd8cbc7a10a62fa5b19d2a68f03cb4
dist     : [zip] https://api.github.com/repos/SendCloud/sendcloud/zipball/0765af9337cd8cbc7a10a62fa5b19d2a68f03cb4 0765af9337cd8cbc7a10a62fa5b19d2a68f03cb4
names    : sendcloud/sendcloud

autoload
files
psr-4
SendCloud\SendCloud\ => .

requires
php ~7.0|~7.1|~7.2|~7.3|~7.4

requires (dev)
phpunit/phpunit ^5.7 || ^6.5 || ^7.1

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
