### ISSUE TITLE
Error when upgrading to version 1.8.3 (using Composer)

### ISSUE THREAD

**Issue by michel334** [SendCloud/sendcloud#124]
Error is in Sendcloud version 1.8.3 using composer (magento version 2.3.2)
See also Error when upgrading to version 1.8.2 (using Composer) #122

$ COMPOSER_MEMORY_LIMIT=-1 composer require sendcloud/sendcloud
Using version ^1.8 for sendcloud/sendcloud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals

Updating sendcloud/sendcloud (1.8.0 => 1.8.3): Downloading (100%)
$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
Updating modules:
Schema creation/updates:
SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'sen_condition_name' doesn't exist in table, query was: ALTER TABLE sendcloud_servicepointrate DROP COLUMN sen_condition_name, ADD CONSTRAINT UNQ_C0DB67076EAA5EA868F15196691297E7 UNIQUE KEY (website_id,dest_country_id,dest_region_id,dest_zip,condition_name,condition_value)

**Comment by michel334** [comment]
Tried again today. We now get a different error (repo.magento.com):

[]$ COMPOSER_MEMORY_LIMIT=-1 composer require sendcloud/sendcloud
Using version ^1.8 for sendcloud/sendcloud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating sendcloud/sendcloud (1.8.0 => 1.8.3): Loading from cache
Writing lock file
Generating autoload files
[]$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
Updating modules:
Schema creation/updates:
SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'sen_condition_name' doesn't exist in table, query was: ALTER TABLE `sendcloud_servicepointrate` MODIFY COLUMN `dest_country_id` varchar(4) NOT NULL DEFAULT "0" COMMENT "Destination coutry ISO/2 or ISO/3 code", MODIFY COLUMN `dest_zip` varchar(10) NOT NULL DEFAULT "*" COMMENT "Destination Post Code (Zip)", DROP COLUMN `sen_condition_name`, ADD CONSTRAINT `UNQ_C0DB67076EAA5EA868F15196691297E7` UNIQUE KEY (`website_id`,`dest_country_id`,`dest_region_id`,`dest_zip`,`condition_name`,`condition_value`)

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
