### ISSUE TITLE
Sendcloud 1.8.4 All shipment methods get selected on checkout

### ISSUE THREAD

**Issue by michel334** [SendCloud/sendcloud#125]
On the first page of the checkout, when selecting a shipment method, all shipment methods get selected.
<edited>Also, i am unable to choose a service point for delivery.
Sendcloud 1.8.4 (repo.magento.com)
Magento 2.3.2
See screenshot
![select-bug](https://user-images.githubusercontent.com/6500172/155468940-bceb2775-40e0-480d-becb-eec4edc3a287.png)

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
