### ISSUE TITLE
Info about status module - new partner is Logeecom

### ISSUE THREAD

**Issue by dragonfly4** [SendCloud/sendcloud#126]
Informational message

The last composer release dates from March 2021 so I have opened a ticket to hear what's going on with the Magento integration.

In the past it was https://www.creative-ct.nl who developed this module.

SendCloud has a new partner with the name Logeecom and I assume it's all taking longer than expected. 

So I'm looking forward to updates in this repository from https://github.com/logeecom

Open issues that are linked to stalled maintenance
#125 #124 #122 #123

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
