### ISSUE TITLE
Sendcloud throws error when making a payment 

### ISSUE THREAD

**Issue by bow93** [SendCloud/sendcloud#129]
Right before making a payment, strange thing is that it does seem to work on our staging environment. Shipping method and connection are both disabled when this happens. 

[2022-05-17 07:12:23] main.CRITICAL: Error: Call to undefined method Magento\Sales\Api\Data\OrderItemExtension::setCountryOfManufacture() in /data/web/magento2/vendor/sendcloud/sendcloud/Plugin/Order/OrderItemRepository.php:91
Stack trace:
#0 /data/web/magento2/vendor/sendcloud/sendcloud/Plugin/Order/OrderItemRepository.php(70): SendCloud\SendCloud\Plugin\Order\OrderItemRepository->setCustomAttributes()
#1 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(146): SendCloud\SendCloud\Plugin\Order\OrderItemRepository->afterGetList()
#2 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\ItemRepository\Interceptor->Magento\Framework\Interception\{closure}()
#3 /data/web/magento2/generated/code/Magento/Sales/Model/Order/ItemRepository/Interceptor.php(32): Magento\Sales\Model\Order\ItemRepository\Interceptor->___callPlugins()
#4 /data/web/magento2/vendor/magento/module-sales/Model/Order.php(2168): Magento\Sales\Model\Order\ItemRepository\Interceptor->getList()
#5 /data/web/magento2/vendor/magento/module-sales/Model/Order/ShippingAssignmentBuilder.php(86): Magento\Sales\Model\Order->getItems()
#6 /data/web/magento2/vendor/magento/module-sales/Model/OrderRepository.php(300): Magento\Sales\Model\Order\ShippingAssignmentBuilder->create()
#7 /data/web/magento2/vendor/magento/module-sales/Model/OrderRepository.php(144): Magento\Sales\Model\OrderRepository->setShippingAssignments()
#8 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get()
#9 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent()

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
