### ISSUE TITLE
Error when configuring dynamic-checkout-beta in the Admin (Magento 2.4.3)

### ISSUE THREAD

**Issue by Hayyan-Ebrahem** [SendCloud/sendcloud#130]
When trying to config "dynamic-checkout-beta" in admin:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vendor/sendcloud/sendcloud/view/adminhtml/ui_component/configuration_form.xml" is invalid:
Element 'option': The type definition is abstract.
Line: 168

Verify the XML and try again.

**Comment by ivabocheva** [comment]
Hi Hayyan-Ebrahem, 

15 days ago the master branch was updated with the newest changes regarding dynamic checkout. This means composer is now updated with version Sendcloud 1.8.6. Do you mind retrying the installation and letting us know if you are still running into this issue? 

Kind regards, 

Iva Bocheva (Technical Integration Manager)

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
