### ISSUE TITLE
Issue with Amasty Shipping Rules after updating to 1.8.6

### ISSUE THREAD

**Issue by gjportegies** [SendCloud/sendcloud#133]
For one of our customers we're experiencing a strange bug when upgrading the SendCloud module to 1.8.6.

We're using the Amasty Shipping Rules module to set specific shipping costs for products that'll fit through the mailbox. Before with version 1.8.0 this was working as expected.

I've tested the above on a development environment and confirmed that switching between these versions breaks the rule we've created for the shipping.

**Comment by pkrstojevic-logeecom** [comment]
New version of the plugin released. Closing this issue.
