### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long; 

### ISSUE THREAD

**Issue by IvoJongmans** [SendCloud/sendcloud#139]
Hi,

When running setup:upgrade after installing the latest sendcloud module version (2.0.3) with composer I get this error message: 

Schema creation/updates:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes, query was: CREATE TABLE `sendcloud_shipping_methods` (
`id` int(11)  NOT NULL  AUTO_INCREMENT COMMENT "Primary key",
`store_view_id` int(11)  NOT NULL   COMMENT "Store view ID",
`external_id` varchar(300) NOT NULL  COMMENT "External id",
`delivery_zone_id` varchar(64) NOT NULL  COMMENT "Delivery zone id",
`data` longtext NULL COMMENT "Shipping method data",
`country` varchar(100) NOT NULL  COMMENT "Shipping method country",
`internal_title` varchar(300) NOT NULL  COMMENT "Shipping method internal title",
`external_title` varchar(300) NOT NULL  COMMENT "Shipping method external title",
`shipping_product` varchar(300) NOT NULL  COMMENT "Shipping method shipping product",
`rates_enabled` tinyint(2)  NOT NULL   COMMENT "Shipping method rates enabled",
`delivery_method` varchar(100) NOT NULL  COMMENT "Shipping delivery method",
CONSTRAINT  PRIMARY KEY (`id`),
CONSTRAINT `SENDCLOUD_SHIPPING_METHODS_EXTERNAL_ID` UNIQUE KEY (`external_id`),
FULLTEXT INDEX `SENDCLOUD_SHIPPING_METHODS_EXTERNAL_TITLE_INTERNAL_TITLE` (`external_title`,`internal_title`)
) ENGINE=innodb DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci COMMENT="SendCloud Shipping Methods"

This prevents us from updating the module. When I do a rollback to a previous module version this problem doesn't occur. 

Setup:
Magento 2.3.5
PHP 7.1
MySQL 5.6 (collation utf8_general_ci)

**Comment by logeecom** [comment]
Hi @IvoJongmans,

We just want to inform you that our team is investigating the issue. 

We will keep you posted on the investigation progress.

Best regards.

**Comment by logeecom** [comment]
Hi @IvoJongmans,

Our team managed to reproduce and fix the mentioned issue.

The fix for the reported issue will be included in the release planned for next week.

Best regards.

**Comment by teodoratimoti** [comment]
Hi @IvoJongmans,

The new plugin version 2.0.5 is released on the Magento marketplace - https://marketplace.magento.com/sendcloud-sendcloud.html
Also, the 2.0.5 version is published on GitHub - https://github.com/SendCloud/sendcloud

Thank you,

Best regards.
