### ISSUE TITLE
Unable to select a service point when creating order in backend

### ISSUE THREAD

**Issue by d1m5n** [SendCloud/sendcloud#140]
Our client is using the servicepoint as shipping method.
During checkout the customer is able to select a service point. 

But our client also creates orders manually in the backend.
When selecting sendcloud service point as shipping method, our client isn't able to select a service point.
Its only possible to select the shipping method.

Our client would love to see the possibility to select the service point when creating an backend order.

![image](https://user-images.githubusercontent.com/5171763/195845794-e21db0ea-c66f-4d31-a3ea-953e298d72c8.png)
![image](https://user-images.githubusercontent.com/5171763/195845880-e8281947-6318-4869-bb59-0618246c0de2.png)

**Comment by teodoratimoti** [comment]
Hi @d1m5n ,

We will be looking at the issue you are reporting and get back to you with our findings.

Thank you,

Kind regards.

**Comment by teodoratimoti** [comment]
Dear @d1m5n ,

The request you made requires more investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to support@sendcloud.com

We hope we have informed you sufficiently and wish you a great day!

Kind regards.
