### ISSUE TITLE
Maximum amount 

### ISSUE THREAD

**Issue by d1m5n** [SendCloud/sendcloud#141]
Our client would love to see a setting to limit the servicepoint to a maximum amount.
At this moment it's possible to enable free shipping from amount X.

![image](https://user-images.githubusercontent.com/5171763/195846434-0b9cd905-dc9b-42f4-be6a-6b81b0e46f66.png)

Our client would love to see that packages with a big amount of value, doesn't get dropped at a service point.
Therefor they would love to see a maximum amount setting, which makes the shipping method inactive if order totals are bigger then this value.

**Comment by teodoratimoti** [comment]
Hi @d1m5n,

Thanks for submitting that idea. Our team will review it and process it further.

We will keep you posted about the process of this change request.

We appreciate your recommendation,

Best regards.

**Comment by teodoratimoti** [comment]
Dear @d1m5n , 

The request you made requires more investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to support@sendcloud.com

We hope we have informed you sufficiently and wish you a great day!

Kind regards.
