### ISSUE TITLE
Is Sendcloud compatible with MSI

### ISSUE THREAD

**Issue by sgagence** [SendCloud/sendcloud#142]
Hi,

When trying to ship order from Sendcloud, webservices response is : Shipment can't create : Source item not found by source code: default and sku: ....

Is ther a way to set a source to deduct stock and make sendcloud module compatible with Magento MSI ?

Thanks

**Comment by teodoratimoti** [comment]
Dear @sgagence, 

Thank you for reaching out to us! 

The request you made requires more investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to support@sendcloud.com

We hope we have informed you sufficiently and wish you a great day!

Kind regards
