### ISSUE TITLE
stripos(): Passing null to parameter #1  .... /AdminhtmlBlockHtmlBeforeObserver.php on line 125

### ISSUE THREAD

**Issue by jimihuy** [SendCloud/sendcloud#144]
Magento 2.4.5 ee
Sendcloud 2.0.6

## Error
`Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/share/magento/ee/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125`

## List of enabled modules:
Magento_Store
Magento_AdminAnalytics
Magento_AdminNotification
Magento_AdminGwsConfigurableProduct
Magento_AdminGwsStaging
Magento_Directory
Magento_AdobeIms
Magento_AdobeImsApi
Magento_AdobeStockAdminUi
Magento_MediaGallery
Magento_AdobeStockAssetApi
Magento_AdobeStockClient
Magento_AdobeStockClientApi
Magento_AdobeStockImage
Magento_Theme
Magento_AdobeStockImageApi
Magento_Eav
Magento_Customer
Magento_AdvancedPricingImportExport
Magento_Rule
Magento_Indexer
Magento_Backend
Magento_Amqp
Magento_Config
Magento_Variable
Magento_Authorization
Magento_User
Magento_Cms
Magento_Catalog
Magento_AwsS3CustomerCustomAttributes
Magento_GiftCardImportExport
Magento_Widget
Magento_ImportExport
Magento_AdminAdobeIms
Magento_Backup
Magento_CatalogRule
Magento_Quote
Magento_SalesSequence
Magento_Payment
Magento_Sales
Magento_Bundle
Magento_GraphQl
Magento_BundleImportExport
Magento_BundleImportExportStaging
Magento_CatalogInventory
Magento_CacheInvalidate
Magento_Checkout
Magento_CardinalCommerce
Magento_AdvancedCatalog
Magento_Security
Magento_CmsGraphQl
Magento_EavGraphQl
Magento_Search
Magento_SalesArchive
Magento_CatalogImportExport
Magento_CatalogImportExportStaging
Magento_StoreGraphQl
Magento_CatalogInventoryGraphQl
Magento_CatalogSearch
Magento_CatalogPageBuilderAnalytics
Magento_CatalogPageBuilderAnalyticsStaging
Magento_CatalogUrlRewrite
Magento_Ui
Magento_CustomerCustomAttributes
Magento_Msrp
Magento_CatalogRuleGraphQl
Magento_SalesRule
Magento_Captcha
Magento_Downloadable
Magento_Staging
Magento_GiftCard
Magento_Wishlist
Magento_CatalogGraphQl
Magento_MediaStorage
Magento_Robots
Magento_ConfigurableProduct
Magento_CheckoutAddressSearch
Magento_GiftRegistry
Magento_CheckoutAgreements
Magento_CheckoutAgreementsGraphQl
Magento_CheckoutStaging
Magento_MediaGalleryUi
Magento_CatalogCmsGraphQl
Magento_CmsPageBuilderAnalytics
Magento_CmsPageBuilderAnalyticsStaging
Magento_VersionsCms
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_CompareListGraphQl
Magento_Integration
Magento_ConfigurableImportExport
Magento_CatalogRuleConfigurable
Magento_QuoteGraphQl
Magento_ConfigurableProductSales
Magento_PageCache
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_Csp
Magento_CurrencySymbol
Magento_CustomAttributeManagement
Magento_AdvancedCheckout
Magento_Analytics
Magento_CustomerBalance
Magento_CustomerBalanceGraphQl
Magento_CustomerSegment
Magento_DownloadableGraphQl
Magento_CustomerFinance
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_CatalogWidget
Magento_DeferredTotalCalculating
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_BundleGraphQl
Magento_DirectoryGraphQl
Magento_ProductAlert
Magento_CustomerDownloadableGraphQl
Magento_DownloadableImportExport
Magento_TargetRule
Magento_AdvancedRule
Magento_CatalogCustomerGraphQl
Magento_AdvancedSearch
Magento_Elasticsearch
Magento_Elasticsearch6
Magento_WebsiteRestriction
Magento_ElasticsearchCatalogPermissionsGraphQl
Magento_Email
Magento_EncryptionKey
Magento_Enterprise
Magento_Fedex
Magento_Tax
Magento_GiftCardAccount
Magento_GiftCardAccountGraphQl
Magento_WishlistGraphQl
Magento_Sitemap
Magento_CatalogEvent
Magento_GiftMessage
Magento_GiftMessageGraphQl
Magento_GiftMessageStaging
Magento_UrlRewrite
Magento_GiftRegistryGraphQl
Magento_GiftWrapping
Magento_GiftWrappingGraphQl
Magento_GiftWrappingStaging
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_GoogleGtag
Magento_GoogleOptimizer
Magento_GoogleOptimizerStaging
Magento_GoogleShoppingAds
Magento_Banner
Magento_AsyncOrder
Magento_GraphQlCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_VisualMerchandiser
Magento_RemoteStorage
Magento_CatalogPermissions
Magento_InstantPurchase
Magento_CatalogAnalytics
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleImportExport
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryBundleProductIndexer
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogFrontendUi
Magento_InventoryCatalogSearch
Magento_InventoryCatalogSearchBundleProduct
Magento_InventoryCatalogSearchConfigurableProduct
Magento_ConfigurableProductGraphQl
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductFrontendUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventorySourceSelectionApi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupGraphQl
Magento_Shipping
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_Multishipping
Magento_Webapi
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_Reports
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryQuoteGraphQl
Magento_InventoryRequisitionList
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_InventoryGraphQl
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventoryShippingAdminUi
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventoryInStorePickupFrontend
Magento_InventorySwatchesFrontendUi
Magento_InventoryVisualMerchandiser
Magento_InventoryWishlist
Magento_Invitation
Magento_JwtFrameworkAdapter
Magento_JwtUserToken
Magento_LayeredNavigation
Magento_LayeredNavigationStaging
Magento_Logging
Magento_LoginAsCustomer
Magento_LoginAsCustomerAdminUi
Magento_LoginAsCustomerApi
Magento_LoginAsCustomerAssistance
Magento_LoginAsCustomerFrontendUi
Magento_LoginAsCustomerGraphQl
Magento_LoginAsCustomerLog
Magento_LoginAsCustomerLogging
Magento_LoginAsCustomerPageCache
Magento_LoginAsCustomerQuote
Magento_LoginAsCustomerSales
Magento_LoginAsCustomerWebsiteRestriction
Magento_Marketplace
Magento_MediaContent
Magento_MediaContentApi
Magento_MediaContentCatalog
Magento_MediaContentCatalogStaging
Magento_MediaContentCms
Magento_MediaContentSynchronization
Magento_MediaContentSynchronizationApi
Magento_MediaContentSynchronizationCatalog
Magento_MediaContentSynchronizationCms
Magento_AdobeStockAsset
Magento_MediaGalleryApi
Magento_MediaGalleryCatalog
Magento_MediaGalleryCatalogIntegration
Magento_MediaGalleryCatalogUi
Magento_MediaGalleryCmsUi
Magento_MediaGalleryIntegration
Magento_MediaGalleryMetadata
Magento_MediaGalleryMetadataApi
Magento_MediaGalleryRenditions
Magento_MediaGalleryRenditionsApi
Magento_MediaGallerySynchronization
Magento_MediaGallerySynchronizationApi
Magento_MediaGallerySynchronizationMetadata
Magento_AdobeStockImageAdminUi
Magento_MediaGalleryUiApi
Magento_AwsS3
Magento_MessageQueue
Magento_Weee
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_MsrpStaging
Magento_MultipleWishlist
Magento_SalesGraphQl
Magento_InventoryInStorePickupMultishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_Newsletter
Magento_NewsletterGraphQl
Magento_OfflinePayments
Magento_OfflineShipping
Magento_BannerCustomerSegment
Magento_PageBuilder
Magento_AdminGws
Magento_PageBuilderAnalytics
Magento_CatalogStaging
Magento_PageBuilderAdminGwsAdminUi
Magento_PaymentGraphQl
Magento_PaymentStaging
Magento_Vault
Magento_Paypal
Magento_PaypalGraphQl
Magento_Persistent
Magento_PersistentHistory
Magento_PricePermissions
Magento_DownloadableStaging
Magento_ProductVideo
Magento_ProductVideoStaging
Magento_PromotionPermissions
Magento_BannerGraphQl
Magento_QuoteAnalytics
Magento_QuoteBundleOptions
Magento_QuoteConfigurableOptions
Magento_QuoteDownloadableLinks
Magento_QuoteGiftCardOptions
Magento_InventoryConfigurableProductAdminUi
Magento_QuoteStaging
Magento_ReCaptchaAdminUi
Magento_ReCaptchaCheckout
Magento_ReCaptchaCheckoutSalesRule
Magento_ReCaptchaContact
Magento_ReCaptchaCustomer
Magento_ReCaptchaFrontendUi
Magento_ReCaptchaGiftCard
Magento_ReCaptchaInvitation
Magento_ReCaptchaMigration
Magento_ReCaptchaMultipleWishlist
Magento_ReCaptchaNewsletter
Magento_ReCaptchaPaypal
Magento_ReCaptchaReview
Magento_ReCaptchaSendFriend
Magento_ReCaptchaStorePickup
Magento_ReCaptchaUi
Magento_ReCaptchaUser
Magento_ReCaptchaValidation
Magento_ReCaptchaValidationApi
Magento_ReCaptchaVersion2Checkbox
Magento_ReCaptchaVersion2Invisible
Magento_ReCaptchaVersion3Invisible
Magento_ReCaptchaWebapiApi
Magento_ReCaptchaWebapiGraphQl
Magento_ReCaptchaWebapiRest
Magento_ReCaptchaWebapiUi
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_Reminder
Magento_AwsS3GiftCardImportExport
Magento_RemoteStorageCommerce
Magento_InventoryLowQuantityNotificationAdminUi
Magento_RequireJs
Magento_ResourceConnections
Magento_Review
Magento_ReviewAnalytics
Magento_ReviewGraphQl
Magento_ReviewStaging
Magento_Reward
Magento_RewardGraphQl
Magento_AdvancedSalesRule
Magento_Rma
Magento_RmaGraphQl
Magento_RmaStaging
Magento_ScheduledImportExport
Magento_Rss
Magento_SalesRuleStaging
Magento_BannerPageBuilderAnalytics
Magento_SalesAnalytics
Magento_AsyncOrderGraphQl
Magento_MultipleWishlistGraphQl
Magento_SalesInventory
Magento_CatalogRuleStaging
Magento_RewardStaging
Magento_BannerPageBuilder
Magento_SampleData
Magento_ScalableCheckout
Magento_ScalableInventory
Magento_ScalableOms
Magento_AwsS3ScheduledImportExport
Magento_Elasticsearch7
Magento_SearchStaging
Magento_CustomerAnalytics
Magento_Securitytxt
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_InventoryInStorePickupSalesAdminUi
Magento_AwsS3PageBuilder
Magento_StagingGraphQl
Magento_CatalogStagingGraphQl
Magento_StagingPageBuilder
Magento_CatalogPermissionsGraphQl
Magento_UrlRewriteGraphQl
Magento_Support
Magento_Swagger
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swat
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_CatalogInventoryStaging
Magento_TargetRuleGraphQl
Magento_GiftCardStaging
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_GoogleTagManager
Magento_ThemeGraphQl
Magento_Translation
Magento_ElasticsearchCatalogPermissions
Magento_Ups
Magento_CatalogUrlRewriteStaging
Magento_CatalogUrlRewriteGraphQl
Magento_AsynchronousOperations
Magento_Usps
Magento_GroupedProductStaging
Magento_PaypalCaptcha
Magento_VaultGraphQl
Magento_Version
Magento_CmsStaging
Magento_VersionsCmsPageCache
Magento_VersionsCmsUrlRewrite
Magento_VersionsCmsUrlRewriteGraphQl
Magento_BundleStaging
Magento_InventoryInStorePickupWebapiExtension
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_ConfigurableProductStaging
Magento_CatalogStagingPageBuilder
Magento_WeeeGraphQl
Magento_WeeeStaging
Magento_PageBuilderAdminAnalytics
Magento_CheckoutAddressSearchGiftRegistry
Magento_WishlistAnalytics
Magento_WishlistGiftCard
Magento_WishlistGiftCardGraphQl
Magento_GiftCardGraphQl
PayPal_Braintree
PayPal_BraintreeGraphQl
SendCloud_SendCloud
Temando_ShippingRemover

**Comment by teodoratimoti** [comment]
Hello @jimihuy,

Thank you for reaching out.
Our team will check this issue and we will get back with more information as soon as possible.

Best regards.

**Comment by teodoratimoti** [comment]
Hello @jimihuy ,

Please note that you are using Adobe Commerce ver. 2.4.5 ee (known as Magento Enterprise Edition). This version is not officially supported on the marketplace (https://marketplace.magento.com/sendcloud-sendcloud.html#product.info.details.tech_specs) by Sendclouod. 
Our team has never tested Sendcloud plugin compatibility with this Magento 2 version and thus cannot guarantee full compatibility and support.
Therefore, note that the reported issue is currently not under our scope of work.

If you have any questions or concerns, please let us know.
Kind regards.
