### ISSUE TITLE
Servicepoints data missing in orders

### ISSUE THREAD

**Issue by mikehenze** [SendCloud/sendcloud#145]
Using sendcloud 2.07 and magento 2.4.5p1 and using dynamic checkout with servicepoints.
When an order is placed choosing a servicepoint the actual servicepoint data is missing in magento and also in sendcloud.

![Screenshot (3)](https://user-images.githubusercontent.com/10600315/204826653-37cb21ee-1bda-44ba-a069-ec32d698e671.png)

In the database table "sales_order" all the "sendcloud_service_point*" rows are empty

Edit: Found the cause.
Its https://mageside.com/subscribe-at-checkout-2.html
Also with the latest version
Will disable that for now and search for another solution

**Comment by teodoratimoti** [comment]
Hello @mikehenze ,

Can you confirm that you found that https://mageside.com/subscribe-at-checkout-2.html is causing the issues with Sendcloud plugin?
When you disabled Mageside subscribe at checkout plugin did the Sendcloud plugin work properly?

Our team has never tested Sendcloud plugin compatibility with this Mageside subscribe at checkout plugin and thus cannot guarantee full compatibility and support.

If you have any questions or concerns, please let us know.
Kind regards.

**Comment by mikehenze** [comment]
Yes and the same goes for https://www.ulmod.com/checkout-subcription-for-magento-2.html
Both cause the problem with the missing servicepoint data.

Without them it works fine

**Comment by teodoratimoti** [comment]
Hello @mikehenze ,

Thank you for all the information! The compatibility with these two plugins (https://mageside.com/subscribe-at-checkout-2.html and https://www.ulmod.com/checkout-subcription-for-magento-2.html ) requires more investigation. 

The Sendcloud support team is best to investigate more indepth. Please forward your issue via the Support page in sendcloud: (https://app.sendcloud.com/v2/support) or reach out to support@sendcloud.com (mailto:support@sendcloud.com).


We hope we have informed you sufficiently and wish you a great day!
