### ISSUE TITLE
URGENT - Can't disable the shipping method in dynamic checkout

### ISSUE THREAD

**Issue by marcwales** [SendCloud/sendcloud#146]
Hi, 
I've tried the module to see how it works but it's not ready for real use. 

When i click on disable the shipping method in sendcloud/dynamic_checkout/shops/delivery_method it doesn't disable it on the magento side. I've tried to delete the method and delivery zone in sendcloud but still it appears in the checkout of the website. 
Clients can still access this method while it's not existing on sendcloud. I can't click on publish to send the changes to magento because i've deleted them....

Hope you can help me fast, should have never activated on my live website. 

Rgds, 
Marc

**Comment by teodoratimoti** [comment]
Hello @marcwales 

Thank you for reaching out.
There is a way to disable the Sendcloud plugin in Magento2.
Login to the admin backend and go to Sendcloud plugin and disable the extension (shown in the picture) and save config.

![image](https://user-images.githubusercontent.com/97519286/205972381-7bbea56f-2501-4fed-b050-9d3adbf2d56f.png)

Please clear the cache after these changes.

Also, you can disconnect the integration by going to Sendcloud panel **Settings>Integrations>Your Magento integration**.
When you disconnected the integration you are able to connect the new one and publish the new dynamic checkout configuration.


Please note that if this does not help you our team would need to do a detailed investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe clearly the issue and add examples where possible. 
We hope we have informed you sufficiently and wish you a great day!

Best regards.

**Comment by marcwales** [comment]
Hi,

Thank you for your fast response. I do not wish to disable the integration with magento, i need to send the orders to sendcloud in order to ship them. I just need to disable the dynamic checkout records. On your screenshot, under dynamic checkout i still have the shipping method knowing that i totaly errased it from sendcloud. 

Could you add a shipping method to your dynamic checkout, send to publish to magento and then try to delete it ?

Hope you can help me. 
Rgds, 
Marc

**Comment by teodoratimoti** [comment]
Hello,

If we understood it right you just want to delete dynamic checkout and still synchronize orders to Sendcloud.

If you wish to do this you can remove dynamic checkout zones and delivery methods by going to Sendcloud panel to the Dynamic checkout tab and find your integration.

![image](https://user-images.githubusercontent.com/97519286/206126792-5d8ffd03-b501-481c-b85a-c114d75847dd.png)

Click on three dots and Delete the configuration. This will remove the dynamic checkout configuration and orders will still be synchronized to Sendcloud.

If you have any further questions, please contact us.

Thank you,

Best regards.

**Comment by marcwales** [comment]
Hi,

Thank you for your return. I will try that this afternoon, i was afraid to delete it there because it says "By deleting this shop configuration, you will also delete its associated delivery zones and delivery methods, and will unpublish the configuration from the shop." 

I was afraid it would delete the intergration and stop syncing the orders ;) Should the "disable" option not work on the delivery method ? If it's disable on sendcoud, it should be disable on magento ?  

Rgds, 
Marc

**Comment by teodoratimoti** [comment]
Hello @marcwales ,

There are 2 different things that merchant can do:

You can disconnect/delete the integration by going to Sendcloud panel Settings>Integrations>Your Magento integration.When you disconnect the integration orders would not be synchronized to the Sendcloud since the whole integration is disconnected

You can delete the dynamic checkout configuration ( in the Sendcloud panel > Dynamic checkout tab ) which will only remove the configuration that you published through the Sendcloud panel. Orders will still be synchronized. When you delete the Checkout configuration in the Sendcloud panel, the delete request will eventually be propagated to the integration. The integration will handle delete requests by removing all integration system entities that were created when the Checkout configuration was created.

The integration should not modify or delete any shop configuration data/entities that it did not create when the checkout configuration was created.

We hope that you understood the difference between these two functionalities.

There are no options to disable the delivery methods on Sendcloud panel.

Did this information help you? Did you manage to remove the dynamic checkout configuration?

Best regards

**Comment by marcwales** [comment]
Hi,
Sorry for the late reply, i had several bugs that i couldn't pin point until i uninstalled the sendcloud module 2.0.4. So i've gone back to 1.8 which was the stable version and all the errors dissapeared. I have a clean 2.4.5 magento install with no code modification and only athlete theme and amasty modules. Here are the list of errors : 
1 - Backend/sales/orders/ click on a completed order/shipments/view the page is blank instead of the clients shipment information. 
2 - Frontend/checkout/shipping method the buttons are not clickable anymore to choose the carrier. 
3 - Frontend/checkout/shipping method the popup for choosing the service point doesn't work anymore, it's loaded under very weired. The service point address that i choose is not shown on the checkout page, very confusing.
4 - Frontend/checkout/shipping method css conflict, search bar invisible..etc.
5 - Backend/menu horrible place for the sendcloud menu button, i click on it everytime i want to click on stores/config... which is a lot. Way better the old place in store/config/sales/sendcloud.

I'll wait for the newer version hoping you guys go back to what was working on 1.8. 

Regards, 
Sidney

**Comment by teodoratimoti** [comment]
Hello @marcwales ,

Thank you very much for all the required information.
Please note that our team doesn't provide support for the 1.8 Sendcloud plugin. (older plugins)
One of the prerequisites for full support is that you have the newest plugin installed, which is currently v2.0.8.

We are always upgrading the plugin and with every new version of it, we are making sure that it is better than the previous one.

For every issue that you face with the newest plugin, you can freely report it here on GitHub or if the issue requires further investigation you can forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe clearly the issue and add examples where possible. 
We hope we have informed you sufficiently and wish you a great day!

Best regards.
