### ISSUE TITLE
Selected shipping method codes differ from available shipping method codes

### ISSUE THREAD

**Issue by DuckThom** [SendCloud/sendcloud#147]
I'm working on a GraphQL based checkout for a Magento 2.4.5 shop in combination with Sendcloud dynamic checkout shipping methods and I noticed that the carrier and method codes change when setting the shipping method on the cart. In the cart response, on the shipping address, there's 2 fields: `availableShippingMethods` and `selectedShippingMethod`.

![image](https://user-images.githubusercontent.com/6512901/207566612-a5705b56-c644-4a40-aa31-946ad3017074.png)

At the top you can see the `carrierCode` and `methodCode` of the `selectedShippingMethod` field, at the bottom the same fields but then from the `availableShippingMethods` item.

To set the shipping method we use the `setShippingMethodOnCart` GraphQL mutation with the carrier and method code from the availableShippingMethods field. However, when we then look at the returned cart's selectedShippingMethod, the codes do not match.

The request:

![image](https://user-images.githubusercontent.com/6512901/207567465-01be4ac8-ca9d-4cfa-a219-cb4471bb9bb1.png)

The response:

![image](https://user-images.githubusercontent.com/6512901/207567620-be0a6fdf-0a35-4dee-bdaf-6d8803998608.png)

This makes it impossible to pre-select the selected shipping method in the shipping step of the checkout as we cannot match the carrier and/or method code against the available methods.

**Comment by teodoratimoti** [comment]
Hello @DuckThom 

Thank you for reaching out.

Please note that our team will check this issue and we will get back to you with an update as soon as possible

Kind regards.

**Comment by DuckThom** [comment]
@teodoratimoti I've been informed by Magento that it's a unspoken/undocumented rule that carrier codes may not contain underscores. For reference, `tig_postnl` also has the same issue. In that module, a workaround was implemented: https://github.com/tig-nl/postnl-magento2/blob/master/Plugin/Order/ShipmentPlugin.php#L53

**Comment by teodoratimoti** [comment]
Hello @DuckThom,

Please note that our team is still working on this issue.
We will keep you posted about the progress.

Best regards.

**Comment by teodoratimoti** [comment]
Dear @DuckThom,

Thank you for your patience.

The request you made requires more investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

We hope we have informed you sufficiently and wish you a great day!

Kind regards.
