### ISSUE TITLE
Cannot connect to Sendcloud

### ISSUE THREAD

**Issue by mtjweb** [SendCloud/sendcloud#148]
I installed the module, but when I press the button "Connect to Sendcloud" only a new empty tab opens.

Magento 2.4.4-p2
Plugin ver. 2.0.8
PHP ver. 7.4.33

Any idea what the problem could be?

**Comment by teodoratimoti** [comment]
Hello @mtjweb ,

Thank you for reaching out. This is just a quick note to inform you that we received your ticket.

Our team started working on this issue.
We will notify you as soon as we have more information.

Best regards.

**Comment by teodoratimoti** [comment]
Dear @mtjweb,

Our team tried to reproduce this issue in our local environment with the setup you described (Magento 2.4.4-p2,
Plugin ver. 2.0.8, PHP ver. 7.4) and we did not succeed in it.

The request you made requires more investigation. The [Sendcloud](https://app.sendcloud.com/v2/support) support team is best to investigate more in-depth. Please forward your request via the Support page in sendcloud: Sendcloud or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe clearly the issue and add examples where possible. 
We hope we have informed you sufficiently and wish you a great day!

Best regards.
