### ISSUE TITLE
Shipments not showing correctly

### ISSUE THREAD

**Issue by gjportegies** [SendCloud/sendcloud#150]
```
main.INFO: Broken reference: the 'bundle' element cannot be added as child to 'shipment_items', because the latter doesn't exist [] []
```

**Used versions**
- Magento Version number(eg 2.3.5): 2.4.3-p3
- Open source/Enterprise/B2b: Open source
- Sendcloud version number: 2.0.11

| Result             |  Expected |
:-------------------------:|:-------------------------:
![sendcloud-shipping-error-2](https://user-images.githubusercontent.com/6707410/218257470-02cd74cc-a0ea-48a2-8146-95c5f7992e91.png) | ![sendcloud-shipping-expected-output](https://user-images.githubusercontent.com/6707410/218257546-6a046ba9-7510-4858-9ba1-f74cf7d47b69.png)

**Additional context**
We're also using the PostNL extension since we were using this before (and still need it for the address validation in the checkout). But even when disabling this module this issue occurs.

**Comment by teodoratimoti** [comment]
Hello @gjportegies,

Thank you for reaching out.

Our team will check this issue and we will get back to you as soon as possible.

Best regards.

**Comment by aweb3r** [comment]
Same in Adobe Commerce 2.4.3

**Comment by Kevin9131** [comment]
We are also experiencing this issue. Could this issue be re-opened?

**Comment by tanjalog** [comment]
Thank you @gjportegies and all others for your feedback.

We appreciate it.

This issue is fixed and will be available in a new release next week.

All the best

**Comment by teodoratimoti** [comment]
Hello @gjportegies  @Kevin9131 @aweb3r ,

Please note that the new plugin version 2.0.13 is released on the [Marketplace](https://marketplace.magento.com/sendcloud-sendcloud.html) and [GitHub](https://github.com/SendCloud/sendcloud/releases/tag/2.0.13).
Best regards.
