### ISSUE TITLE
Wrong Sendcloud shipping method column order

### ISSUE THREAD

**Issue by gjportegies** [SendCloud/sendcloud#154]
In the `sc-method-list-template.html` file the columns are in the a different order than in the `sc-method-item-template.html` file.

![Screenshot 2023-03-20 at 15 26 19](https://user-images.githubusercontent.com/6707410/226372447-d0c3fb17-0b9e-41c8-8ef3-f09858c46ef0.png)

**Price as 2nd column**
https://github.com/SendCloud/sendcloud/blob/3debe345cf1ffcc705efd7e6dbf0b6cd03fcd650/view/frontend/web/template/sc-method-list-template.html#L4-L9

**Price as 4th column**
https://github.com/SendCloud/sendcloud/blob/3debe345cf1ffcc705efd7e6dbf0b6cd03fcd650/view/frontend/web/template/sc-method-item-template.html#L2-L38

**Comment by teodoratimoti** [comment]
Hello @gjportegies  ,

Thank you for reaching out. This is just a quick note to inform you that we received your issue and have already started working on it.

If you have any further questions or concerns, please let us know.

Best regards.

**Comment by teodoratimoti** [comment]
Hello @gjportegies ,

Please note that a new plugin release is created 2.0.14

GitHub: https://github.com/SendCloud/sendcloud/releases/tag/2.0.14

Marketplace: https://marketplace.magento.com/sendcloud-sendcloud.html

Best regards.

Thank you for bringing this to our attention.
