### ISSUE TITLE
PHP error: Argument ($array) must be of type array

### ISSUE THREAD

**Issue by jeroen-dhm** [SendCloud/sendcloud#155]
When using PHP version 8.1 with the Sendcloud module, an error is thrown when the customer selects a servicepoint:

```TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /data/web/magento2/vendor/sendcloud/sendcloud/Plugin/CheckoutBeforeSaveShippingInformation.php:85```

**Comment by teodoratimoti** [comment]
Hello @jeroen-dhm ,

Please note that our team fix the issue and we will notify you when we release the new plugin version.

Best regards.
