### ISSUE TITLE
Improvement: Pick-up shops by attribute

### ISSUE THREAD

**Issue by tropilex** [SendCloud/sendcloud#156]
**The problem:**

Carriers do not allow large items to be sent to a pickup shops. For example, an item measuring 160 x 30 x 30 cm can be sent to a home address but is not allowed by official rules to most pickup shops. 

With the Sendcloud module you can only show the method based on price or weight (table rates). But not by package size.

So we have customers who choose to send a large package to a parcel shop. Then the package gets stuck in a depot somewhere. 

**Solution:** 

A solution could be that based on a Magento product attribute "Parcelshop allowed" the method is shown or not.

**Comment by teodoratimoti** [comment]
Hello @tropilex,

Thank you for reaching out.

Our team will check this matter and we will provide you we the response as soon as possible.

Best regards.

**Comment by teodoratimoti** [comment]
Hello @tropilex,

Our team reviewed the improvement request.

The request you made requires more investigation. The Sendcloud support team is best to investigate more indepth. Please forward your request via the Support page in sendcloud: [Sendcloud](https://app.sendcloud.com/v2/support) or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe the enhancement you propose and add examples where possible. 
We hope we have informed you sufficiently and wish you a great day!
