### ISSUE TITLE
When using Mageplaza OneStepCheckout you can process order without selecting pickup point

### ISSUE THREAD

**Issue by LucasVollebergh** [SendCloud/sendcloud#157]
Placing an order with Pickup Point Method selected but no specific Pickup point selected is possible. 
**how it should work:** should not be able to process an order without selecting a pickup point. 

This is combined with the Mageplaza OneStepCheckout module 

![image](https://github.com/SendCloud/sendcloud/assets/13552277/d1fec538-80ed-416d-a988-1d19ba871839)

**Comment by logeecom** [comment]
Dear user, 

Thank you for reaching out to us! 

The request you made requires more investigation. The Sendcloud support team is best to investigate more in-depth.

Please forward your request via the Support page in SendCloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

If possible please describe clearly the issue and add examples where possible as you already did.

We hope we have informed you sufficiently and wish you a great day!
