### ISSUE TITLE
Unable to apply data patch

### ISSUE THREAD

**Issue by SteelDragoncc** [SendCloud/sendcloud#159]
Everytime we install this module we have this error.
How to fix?
Unable to apply data patch SendCloud\SendCloud\Setup\Patch\Data\UpdateInternationalShipping for module SendCloud_Send                                                                                                                        Cloud. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '11-General'                                                                                                                         for key 'eav_attribute_group.EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: UPDATE `eav_attr                                                                                                                        ibute_group` SET `attribute_set_id` = ?, `attribute_group_name` = ?, `default_id` = ? WHERE (`attribute_group_id`='50                                                                                                                        ')

**Comment by tanjalog** [comment]
Hello, @SteelDragoncc 

Thanks for reaching out to us.

Please note that we will investigate the issue you reported and get back to you soon.

Best regards

**Comment by tanjalog** [comment]
Dear @SteelDragoncc 

The request you made requires more investigation.

The Sendcloud support team is best to investigate more in-depth. Please forward your request via the Support page in sendcloud: https://app.sendcloud.com/v2/support or reach out to [support@sendcloud.com](mailto:support@sendcloud.com).

That way you can share more credentials if needed.

If possible please describe clearly the issue, Magento version you are using, whether is it CE or EE plugin version, php you are using etc that can be useful for investigation.

We hope we have informed you sufficiently and wish you a great day!
