### ISSUE TITLE
Version 2.0.20 not on github?

### ISSUE THREAD

**Issue by hostep** [SendCloud/sendcloud#162]
Hi guys

Version 2.0.20 of this module is available on https://commercemarketplace.adobe.com/sendcloud-sendcloud.html, but not here in github? This is kind of confusing...
Any chance you'll push version 2.0.20 here as well soon-ish?

Thanks!

**Comment by tanjalog** [comment]
Hi @hostep 

Please note that the new version of plugin v2.0.20 is available on the github.

Thank you.

Best regards

**Comment by hostep** [comment]
Thanks for the update @tanjalog!

I see a tag was pushed indeed: https://github.com/SendCloud/sendcloud/tags, but no new release was created: https://github.com/SendCloud/sendcloud/releases
However, that's not super important, it would just be nice to stay consistent with your older releases :)

I'll close this issue now 🙂
