### ISSUE TITLE
Wrong translation dutch file

### ISSUE THREAD

**Issue by abovowebdevelopment** [SendCloud/sendcloud#163]
Hi,

In /i18n/nl_NL.csv:109 there's a typo in the translations.
` %sstore_name` should be ` %store_name`

**Comment by logeecom** [comment]
Hi @abovowebdevelopment ,

Thanks for reaching out to us.

We are checking the typo in the translation you reported and we will update you soon.

**Comment by logeecom** [comment]
Hi @abovowebdevelopment,

The typo in In /i18n/nl_NL.csv:109 has been corrected and released.

Thank you,

Best regards.
