### ISSUE TITLE
Hyva checkout compatibility?

### ISSUE THREAD

**Issue by allrude** [SendCloud/sendcloud#164]
Would be nice to have a Integration with Hyva checkout (https://www.hyva.io/hyva-checkout.html)
can be done by building a Hyvä Compatibility Module see: https://docs.hyva.io/hyva-themes/compatibility-modules/index.html

Perhaps you are already working on that would be nice to get some info

**Comment by logeecom** [comment]
Hi @allrude 

Thanks for reaching out to us.

We will update you soon with more details.

Best regards

**Comment by allrude** [comment]
Meanwhile I got the information that a third party developed a Sendcloud Hyvä compatibility module, you can find it here:

https://github.com/bethlehemit/HyvaSendcloud

**Comment by logeecom** [comment]
Hey @allrude Please note that our team needs more time to investigate this topic. We will keep you posted.

Best regards.

**Comment by logeecom** [comment]
Hey @allrude 
Our team has thoroughly reviewed this matter, and we want to share that it is on our roadmap for 2024. We will work on realizing this in the upcoming year. Thanks a lot for bringing this up.
Best regards.
