### ISSUE TITLE
Error Element 'route', attribute 'method': The attribute 'method' is not allowed.

### ISSUE THREAD

**Issue by ithuis** [SendCloud/sendcloud#165]
Updated to latest version, now i get this error

The XML in file "/var/www/html/vendor/sendcloud/sendcloud/etc/frontend/routes.xml" is invalid:
Element 'route', attribute 'method': The attribute 'method' is not allowed.
Line: 7

**Comment by logeecom** [comment]
Hello @ithuis 

Thank you for reaching out.

Please note that our team will check this and we will update you with more information.

Best regards.

**Comment by onepack** [comment]
Same here. Frontend broken due to Sendcloud routes.xml
